"""empty message

Revision ID: feff04a84dd2
Revises: 
Create Date: 2019-03-24 17:38:30.384168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feff04a84dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ListMobil', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('ListMobil', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ListMobil', sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('ListMobil', 'user_id')
    # ### end Alembic commands ###
